# Generated by Django 2.2.6 on 2019-10-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieBookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('bookmark_id', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('popularity', models.FloatField()),
                ('releaseDate', models.CharField(max_length=25)),
            ],
        ),
    ]
